name: Build Release

on:
  push:
    branches:
      - main

permissions:
  contents: write


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # gradle build
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew fatJar

      - name: Build with Gradle
        run: ./gradlew version > version.txt

      - name: Set output
        run: echo "version=$(grep -o 'v[0-9]\+\.[0-9]\+\.[0-9]\+' version.txt | head -n 1)" >> $GITHUB_OUTPUT
        id:  version

      - name: log the output version
        run: echo ${{ steps.version.outputs.version }}


      # upload build artifacts
      - name: List build/libs contents
        run: ls -R build/libs

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
         name: build-artifacts
         path: |
          build/libs/
          version.txt

  release:
      needs: build
      if: ${{ success() }}
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Download build artifacts
          uses: actions/download-artifact@v3
          with:
            name: build-artifacts

        - name: Read version from file
          id: version
          run: echo "version=$(grep -o 'v[0-9]\+\.[0-9]\+\.[0-9]\+' version.txt | head -n 1)" >> $GITHUB_OUTPUT

        # output the version
        - name: log the output version
          run: echo ${{ steps.version.outputs.version }}
        # check the version is valid
        - name: Check version is valid
          run: |
            if [ -z "${{ steps.version.outputs.version }}" ]; then
              echo "Version not found."
              exit 1
            fi

        - name: Bump version and push tag
          id: tag
          uses: anothrNick/github-tag-action@1.67.0
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            WITH_V: true
            CUSTOM_TAG: ${{ steps.version.outputs.version }}

        - name : output the tag
          run: echo "tag=${{ steps.tag.outputs.new_tag }}" >> $GITHUB_OUTPUT

        - name: Release
          uses: softprops/action-gh-release@v1
          with:
            files: |
              build/libs/*
            tag_name: ${{ steps.tag.outputs.new_tag }}
