name: Build Release

on:
  push:
    branches:
      - main

permissions:
  contents: write


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Gradle Perms
        run: chmod +x ./gradlew

      - name: Get Version
        run: ./gradlew version > version.txt

      - name: Check version file contents
        run: cat version.txt

      - name: Check Version isnt empty
        run: if [ -s version.txt ]; then echo "version.txt is not empty"; else echo "version.txt is empty"; exit 1; fi

      - name: Set output to env
        run: echo "VERSION=$(cat version.txt | tr -d '[:space:]')" >> $GITHUB_ENV
        id: version

      - name: Read version output
        run: echo "Version is ${{ env.VERSION }}"

      - name: Check if version is valid
        run: |
          if [ -z "${{env.version}}" ]; then
            echo "Version not found."
            exit 1
          fi

      - name: Build with Gradle
        run: ./gradlew fatJar

      - name: Bump version and push tag
        id: tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          CUSTOM_TAG: ${{ env.VERSION }}

      - name : output the tag
        run: echo "tag=${{ steps.tag.outputs.new_tag }}" >> $GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/libs/*
          tag_name: ${{ steps.tag.outputs.new_tag }}

      ## Publish to GitHub Packages
      - name: Publish to GitHub Packages
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
